# Project information
site_name: 'Loki Docs'
site_url: 'https://loki-project.github.io/loki-docs/'

# Repository
repo_name: 'lokidocs'
repo_url: 'https://github.com/loki-project/loki-docs'

# Copyright
copyright: 'Add Copyright'


# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
     accent: 'green'

  font:
    title: 'Proxima Nova'
    text: 'Roboto Regular'
    code: 'Roboto'
  favicon: 'Loki_favicon32x32.png'
  logo: 'Loki_favicon32x32.png'

nav:
- 'Home': 'index.md'
- Introduction:
  - 'Overview': 'Introduction/Overview.md'
  - 'Where to begin?': 'Introduction/BeginnersGuide.md'
- Wallets: 
  - 'Overview' : 'Wallets/WalletsOverview.md'
  - 'What wallet to use?' : 'Wallets/WhatWalletToUse.md'
  - Web Wallet (LokiLocker): 
      - 'WW Overview' : 'Wallets/WebWallet/WebWalletOverview.md'
      - 'Guides': 'Wallets/WebWallet/Guides.md'
  - Graphical User interface (GUI) Wallet:
      - 'GUI Overview' : 'Wallets/GuiWallet/GUIOverview.md'
      - 'Guides': 'Wallets/GuiWallet/Guides.md'
  - Mobile Wallet:
      - 'Mobile Wallet Overview' : 'Wallets/MobileWallet/MobileWalletOverview.md'
      - 'Android Wallet Guide' : 'Wallets/MobileWallet/Guides.md'
  - Command Line Integrated (CLI) Wallet:
      - 'CLI Overview' : 'Wallets/CliWallet/CLIOverview.md'
      - Guides:
        - 'CLI Mac Setup': 'Wallets/CliWallet/loki-wallet-cliMacSetup.md'
        - 'CLI Wallet Commands': 'Wallets/CliWallet/WalletCommands.md'
        - Multisig:
           - '2/2 Multisig': 'Wallets/CliWallet/2of2Multisig.md'
           - '2/3 Multisig': 'Wallets/CliWallet/2of3Multisig.md'

  - 'Multsigniture': 'Wallets/Multisigniture.md'
- Mining:
   - 'Proof Of Work': 'Mining/ProofOfWork.md'
   - 'ASIC Resistance': 'Mining/ASICResistance.md'
- Service Nodes:
    - 'Overview': 'ServiceNodes/SNOverview.md'
    - 'Staking Requirement': 'ServiceNodes/StakingRequirement.md'
    - Guides:
      - 'Service Node Full Guide': 'ServiceNodes/SNFullGuide.md'
      - 'Service Node RPC Guide': 'Advanced/SNRPCGuide.md'
      - 'Service Node As Service Guide': 'ServiceNodes/RunServiceNodeAsService.md'
- Lokinet:
    - 'Overview': 'Lokinet/LokinetOverview.md'
    - Loki Services:
       - 'SNApps': 'Lokinet/SNapps.md'
       - 'Messenger' : 'Lokinet/Messenger.md'
       - 'Exit Nodes': 'Lokinet/ExitNodes.md'
       - 'Remote Nodes': 'Lokinet/RemoteNodes.md'
       - 'Blink': 'Lokinet/Blink.md'
    - 'LLARP': 'Lokinet/LLARP.md'
    - 'Developers': 'Lokinet/DeveloperInfo.md'
    - Guides:
        - 'Test Network Relay': 'Lokinet/Guides/TestNetRelay.md'
        - 'SNApps': 'Lokinet/Guides/SNApps.md'
        - 'Exit Nodes': 'Lokinet/Guides/ExitNode.md'
- Advanced:
    - 'Technical Specs' : 'Advanced/TechnicalSpecs.md'
    - 'Emission Curve' : 'Advanced/EmissionCurve.md'
    - 'Sybil Resistance' : 'Advanced/SybilResistance.md'
    - 'Dynamic Block Size': 'Advanced/DynamicBlockSize.md'
    - 'CryptoNote Elements': 'Advanced/CryptoNoteElements.md'
    - Attack Prevention:
        - 'Denial of Service Attacks': 'Advanced/DenialofServiceAttacks.md'
        - 'IP and Packet Blocking': 'Advanced/IPandPacketBlocking.md'
        - 'Swarm Flagging': 'Advanced/SwarmFlagging.md'
    - Guides:
        - 'lokid' : 'Advanced/lokid.md'
        - 'Compiling Loki from source': 'Advanced/CompilingGuide.md'
        - 'Using Lokinet': 'Advanced/UsingLokinet.md'
        - 'Using Tor': 'Advanced/UsingTor.md'
        - 'Debugging': 'Advanced/Debugging.md'  
        - 'Service Node RPC Guide': 'Advanced/SNRPCGuide.md'      
- 'FAQ': 'FAQ.md'
- Contributing:
   - 'Using Github': 'Contributing/Github.md'
   - 'Vulnerability Response': 'Contributing/VULNERABILITY_RESPONSE_LOKI.md'
- About:
   - 'Governance': 'About/Governance.md'
   - 'The Loki Foundation': 'About/TheLokiFoundation.md'
   - 'Loki Funding System': 'About/LokiFundingSystem.md'

# Customization
extra_css:
  - CSS/style.css
  - CSS/font.css

extra:
  social:
    - type: 'github'
      link: 'https://github.com/loki-project'
    - type: 'twitter'
      link: 'https://twitter.com/loki_project'
    - type: 'telegram'
      link: 'https://t.me/LokiCommunity'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/LokiProject'
    - type: 'youtube'
      link: 'https://www.youtube.com/lokinetwork'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

